language: python

python:
    - 2.7
    - 3.4
    - 3.5
    # This is just for "egg_info".  All other builds are explicitly given in the matrix
env:
    global:
        # Set defaults to avoid repeating in most cases
        - NUMPY_VERSION=1.10
        - MAIN_CMD='python setup.py'

matrix:
    include:

        # Try all python versions with the latest numpy
        - python: 2.7
          env: SETUP_CMD='test --coverage'
        - python: 3.4
          env: SETUP_CMD='test --coverage'
        - python: 3.5
          env: SETUP_CMD='test --coverage'

before_install:

    # Use utf8 encoding. Should be default, but this is insurance against
    # future changes
    - export PYTHONIOENCODING=UTF8
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=/home/travis/miniconda2/bin:$PATH
    - conda update --yes conda

    # UPDATE APT-GET LISTINGS
    - sudo apt-get update

install:

    # CONDA
    - conda create --yes -n test python=$TRAVIS_PYTHON_VERSION
    - source activate test

    # CORE DEPENDENCIES
    - conda install --yes numpy=$NUMPY_VERSION pytest pip yt astropy

    # COVERAGE DEPENDENCIES
    - if [[ $SETUP_CMD == 'test --coverage' ]]; then pip install coverage coveralls; fi

script:
    - $MAIN_CMD $SETUP_CMD

after_success:
    - if [[ $SETUP_CMD == 'test --coverage' ]]; then coveralls --rcfile='astropy/tests/coveragerc'; fi
